Started by user [8mha:////4AvbKtqCpWGC4/9vlaAOyQD+y56HOfLOpPpkD7K9YRsAAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
Running as SYSTEM
Building in workspace /var/root/.jenkins/workspace/hot_user
using credential root
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:kirinisland/zaoci-tool.git # timeout=10
Fetching upstream changes from git@github.com:kirinisland/zaoci-tool.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:kirinisland/zaoci-tool.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision b8225cdccd06453ebd834839bcf9a9f3cea9d9f1 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f b8225cdccd06453ebd834839bcf9a9f3cea9d9f1 # timeout=10
Commit message: "fix hot user bug"
 > git rev-list --no-walk 49077f5e57d92eaeb3f4fb3c8d5df199fa68e17a # timeout=10
[hot_user] $ /bin/sh -xe /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/jenkins6692751930533594121.sh
+ '[' -z '' ']'
+ echo 'Fetch with specific date!'
Fetch with specific date!
+ python3 jobs/hot_user.py --date
usage: hot_user.py [-h] [-a APPLICATION_ID] [-r REST_API_KEY] [-d DATE]
hot_user.py: error: argument -d/--date: expected one argument
Build step 'Execute shell' marked build as failure
Finished: FAILURE
