Started by upstream project "[8mha:////4A+bQWpgGeLrf62Kvp9R0kchXAV8l6qMSbpRKFffssHgAAAAnR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzuEgZB/az8JP2UxJJE3aLSvLzUIn0A55yqqsYAAAA=[0mdata-runner" build number [8mha:////4HYnbOK2yJKrYvu9FlmWXzfcrajHsRWmAAd3a/DPgB9AAAAAnB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLQAygGfpZ+Un6KYklibpFpXl5qUX6ZgB6zjkXxwAAAA==[0m6
originally caused by:
 Started by user [8mha:////4AvbKtqCpWGC4/9vlaAOyQD+y56HOfLOpPpkD7K9YRsAAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
Running as SYSTEM
Building in workspace /var/root/.jenkins/workspace/data-shuochang
using credential root
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:kirinisland/datapipe.git # timeout=10
Fetching upstream changes from git@github.com:kirinisland/datapipe.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:kirinisland/datapipe.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 8862dc0b93faeb24f71cee4ff5c950ac2bc56c56 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 8862dc0b93faeb24f71cee4ff5c950ac2bc56c56 # timeout=10
Commit message: "update log"
 > git rev-list --no-walk 3b56e1389a2f9aeae1cb5cd946f48ff1e4df7866 # timeout=10
[data-shuochang] $ /bin/sh -xe /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/jenkins2519181990496026631.sh
+ set -x
+ date_str=
+ '[' '' = '' ']'
++ date +%Y%m%d
+ date_str=20210418
+ output_dir=/Users/hongliang/media/storage/production_data/original_lyric/20210418
+ mkdir -pv /Users/hongliang/media/storage/production_data/original_lyric/20210418
+ python3 runner_qq.py --method search --query $'\350\257\264\345\224\261' --output-suffix shuochang --dump-raw 1 --dump-seg 0 --proxy
INFO:[DataPipeline]:Start crawling for query: ËØ¥Âî±
INFO:[DataPipeline]:Processing playlist page: 0, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 1, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 2, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 3, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 4, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 5, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 6, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 7, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 8, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 9, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 10, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 11, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 12, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 13, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 14, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 15, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 16, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 17, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 18, found 47 playlists
INFO:[DataPipeline]:Processing playlist page: 19, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 20, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 21, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 22, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 23, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 24, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 25, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 26, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 27, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 28, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 29, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 30, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 31, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 32, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 33, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 34, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 35, found 47 playlists
INFO:[DataPipeline]:Processing playlist page: 36, found 4 playlists
INFO:[DataPipeline]:Processing playlist page: 37, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 38, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 39, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 40, found 19 playlists
INFO:[DataPipeline]:Processing playlist page: 41, found 47 playlists
INFO:[DataPipeline]:Processing playlist page: 42, found 18 playlists
INFO:[DataPipeline]:Processing playlist page: 43, found 42 playlists
INFO:[DataPipeline]:Processing playlist page: 44, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 45, found 3 playlists
INFO:[DataPipeline]:Processing playlist page: 46, found 20 playlists
INFO:[DataPipeline]:Processing playlist page: 47, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 48, found 18 playlists
INFO:[DataPipeline]:Processing playlist page: 49, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 50, found 0 playlists
INFO:[DataPipeline]:Total playlists found about topic: ËØ¥Âî±: 2235
INFO:[DataPipeline]:PlayList: [3756838699] ÊäñÈü≥ÁÉ≠Èó®ÁöÑ‰∏≠ÊñáËØ¥Âî±Ê≠åÊõ≤ (0/2235) has 83 songs.
INFO:[DataPipeline]:PlayList: [7826295367] 2020ËØ¥Âî±&#32;Top&#32;100 (1/2235) has 100 songs.
INFO:[DataPipeline]:PlayList: [7279190816] ‰∏≠ÂõΩÊñ∞ËØ¥Âî± (2/2235) has 70 songs.
INFO:[DataPipeline]:PlayList: [7142609344] ÂõΩ‰∫ßËØ¥Âî±ÔΩúËøôÊâçÊòØ‰∏≠ÂõΩrapper (3/2235) has 147 songs.
INFO:[DataPipeline]:PlayList: [7547480694] ‰∏≠ÊñáËØ¥Âî±&#32;&#124;&#32;ËäÇÂ•è‰∏≠ÊÑüÂèóÊΩÆÊµÅ (4/2235) has 100 songs.
INFO:[DataPipeline]:PlayList: [7781650183] ÂõΩËØ≠ËØ¥Âî±&#32;&#124;&#32;ÈÖ∑ÊãΩÊäºÈüµ‰Ω†Áà±‰∫ÜÂòõÔºÅ (5/2235) has 548 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=7122368&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 58, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-shuochang/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-shuochang/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=7122368&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 68, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ProxyError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=7122368&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))")),)
INFO:[DataPipeline]:PlayList: [7025601600] ËÆ©‰Ω†Â∞èÈπø‰π±ÊíûÁöÑÊÉÖÊ≠åËØ¥Âî± (6/2235) has 65 songs.
INFO:[DataPipeline]:PlayList: [7252362363] ÂçéËØ≠Rap&#32;¬∑&#32;Âê¨ÁÉ≠Ë°ÄËà¨ÊäºÈüµËØ¥Âî±ËäÇÂ•è (7/2235) has 46 songs.
INFO:[DataPipeline]:PlayList: [2966940676] „ÄåËØ¥Âî±„ÄçÂòªÂìàÂî±Â∞ÜÂ∏¶‰Ω†Âó®‰∏äÂ§© (8/2235) has 146 songs.
INFO:[DataPipeline]:PlayList: [7667588752] „ÄåË∂ÖÁÅ´rap„Äç‰∏ÄËµ∑ËØ¥Âî±ÁáÉÁÇ∏ËàûÂè∞ (9/2235) has 92 songs.
INFO:[DataPipeline]:Sleep for: 51
INFO:[DataPipeline]:PlayList: [7492936955] ÊäñÈü≥ÁÉ≠Èó®Ëã±ÊñáËØ¥Âî±ÂêàÈõÜ (10/2235) has 225 songs.
INFO:[DataPipeline]:PlayList: [7718803579] HIP&#45;HOP&#32;&#124;&#32;ÊóãÂæãËØ¥Âî±ÁöÑÂ§©Â†Ç (11/2235) has 60 songs.
INFO:[DataPipeline]:PlayList: [7488775647] ‰∏≠ÊñáËØ¥Âî±&#32;&#124;&#32;ÈùûÊàòÊñó‰∫∫ÂëòËØ∑Êí§Á¶ª (12/2235) has 100 songs.
INFO:[DataPipeline]:PlayList: [7948555084] ‰∏ÄÂë®ÁöÑËØ¥Âî±Ê≠åÊâã&#32;&#124;&#32;ÁÇ∏Âú∫ÂÄíËÆ°Êó∂ (13/2235) has 41 songs.
INFO:[DataPipeline]:PlayList: [4276387932] ÂÇ∑ÊÑüË™™Âî±‰∏®‰∏çË¶ÅÂÜçÁÇ∫‰ªñÈºªÈÖ∏‰∫Ü (14/2235) has 192 songs.
INFO:[DataPipeline]:PlayList: [7688087842] „ÄäËØ¥Âî±Êñ∞‰∏ñ‰ª£„ÄãÊ≠åÊõ≤ÂêàÈõÜ (15/2235) has 121 songs.
INFO:[DataPipeline]:PlayList: [2058999956] ÂòªÂìàÁºñÂπ¥Âè≤Ôºö100‰ΩçÊ≠åÊâãÁöÑÈúáÊíºËØ¥Âî± (16/2235) has 181 songs.
INFO:[DataPipeline]:PlayList: [7722653258] ÂõΩ‰∫ßËØ¥Âî±ÔºöÂòªÂìàÁé∞Âú∫È•∂Ëàå‰∏çÂñòÊ∞î (17/2235) has 119 songs.
INFO:[DataPipeline]:PlayList: [7707261125] ÁîúÂ∫¶ÁàÜË°®&#32;&#124;&#32;ÊóãÂæãËØ¥Âî±ÁãôÂáªÂ∞ëÂ•≥ÂøÉ (18/2235) has 55 songs.
INFO:[DataPipeline]:PlayList: [7277887376] Ê¨ßÁæéËØ¥Âî±&#124;&#32;Ê∞îÂú∫ÂÖ®ÂºÄ (19/2235) has 43 songs.
INFO:[DataPipeline]:Sleep for: 47
INFO:[DataPipeline]:PlayList: [7509709903] ÂçéËØ≠ËØ¥Âî±&#32;ÔΩú&#32;Èô∑ÂÖ•Âæ™ÁéØÈ£éÊö¥ (20/2235) has 110 songs.
INFO:[DataPipeline]:PlayList: [7673723312] HIP&#45;HOP&#32;&#124;&#32;Ê¨ßÁæéËØ¥Âî±Âú∞Â∏¶ (21/2235) has 81 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=264748266&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 58, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-shuochang/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-shuochang/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=264748266&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 68, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ProxyError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=264748266&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))")),)
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=253570484&_=1513437581324 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 58, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-shuochang/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-shuochang/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=253570484&_=1513437581324 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 68, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (SSLError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=253570484&_=1513437581324 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1056)')))")),)
INFO:[DataPipeline]:PlayList: [7269422312] ‰∏≠ÊñáËØ¥Âî±Âà∂Ë∫Å (22/2235) has 51 songs.
INFO:[DataPipeline]:PlayList: [7686048634] ÊäÄÊúØÊµÅËØ¥Âî±&#32;&#124;&#32;Âê¨ÊúÄHiphopÁöÑÊ≠å (23/2235) has 53 songs.
INFO:[DataPipeline]:PlayList: [7645862005] „Äå‰∏≠ÊñáËØ¥Âî±„ÄçÊé•ËøëÂ§©Ëä±ÊùøÁöÑËØ¥Âî± (24/2235) has 167 songs.
INFO:[DataPipeline]:PlayList: [7222867700] ‰º§ÊÑüÁöÑËØ¥Âî±ÔºåÂç¥Ë∂äÂê¨Ë∂äÂÖ•Ëø∑ (25/2235) has 47 songs.
INFO:[DataPipeline]:PlayList: [7771847257] ‰∏≠ÊñáËØ¥Âî±&#32;&#124;&#32;ÊççÂç´ÊØè‰∏™rapperÊ¢¶ (26/2235) has 189 songs.
INFO:[DataPipeline]:PlayList: [7689561971] „Äå‰∏≠ÊñáËØ¥Âî±„ÄçÊ∞îÂú∫ÂÖ®ÂºÄÔºåË∞Å‰∏é‰∫âÈîã (27/2235) has 209 songs.
INFO:[DataPipeline]:PlayList: [6945092286] ÂçéËØ≠ËØ¥Âî±ÔΩúRap‰πüÂèØ‰ª•ÂæàÂ∏Ö (28/2235) has 70 songs.
INFO:[DataPipeline]:PlayList: [4260105355] ËÄÅÊùøÔºåÊù•ÊùØ7ÂàÜÁîúÁöÑËØ¥Âî±ÊÉÖËØù (29/2235) has 46 songs.
INFO:[DataPipeline]:Sleep for: 67
INFO:[DataPipeline]:PlayList: [7733518961] ËØ¥Âî±Êñ∞‰∏ñ‰ª£ÔΩú&#32;Á¨¨ÂÖ≠Êúü (30/2235) has 25 songs.
INFO:[DataPipeline]:PlayList: [7084698351] È°∂Â∞ñËã±ÊñáËØ¥Âî±&#32;Ëø∞ËØ¥ËäÇÂ•èÈ≠ÖÂäõ (31/2235) has 126 songs.
INFO:[DataPipeline]:PlayList: [7725822437] ËØ¥Âî±Êñ∞‰∏ñ‰ª£ÔΩú&#32;Á¨¨‰∫îÊúü (32/2235) has 23 songs.
INFO:[DataPipeline]:PlayList: [7184384588] &#32;ËÅÜÂê¨99ÔºÖ‰∏≠ÂõΩÂçéËØ≠ËØ¥Âî± (33/2235) has 726 songs.
INFO:[DataPipeline]:PlayList: [7704435941] ÊóãÂæãËØ¥Âî±Ôºörapper‰πüÊúâÊüîÊÉÖ‰∏ÄÈù¢ (34/2235) has 42 songs.
INFO:[DataPipeline]:PlayList: [7744688425] ËØ¥Âî±Êñ∞‰∏ñ‰ª£&#32;&#124;&#32;ÈÄâÊâã‰∏™‰∫∫‰ª£Ë°®‰ΩúÂìÅ (35/2235) has 47 songs.
INFO:[DataPipeline]:PlayList: [7694993918] ÊóãÂæãËØ¥Âî±‚îÇÊÉ≥Ë¶ÅÊàê‰∏∫RapstarÂêóÔºü (36/2235) has 75 songs.
