Started by upstream project "[8mha:////4A+bQWpgGeLrf62Kvp9R0kchXAV8l6qMSbpRKFffssHgAAAAnR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzuEgZB/az8JP2UxJJE3aLSvLzUIn0A55yqqsYAAAA=[0mdata-runner" build number [8mha:////4HYnbOK2yJKrYvu9FlmWXzfcrajHsRWmAAd3a/DPgB9AAAAAnB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLQAygGfpZ+Un6KYklibpFpXl5qUX6ZgB6zjkXxwAAAA==[0m6
originally caused by:
 Started by user [8mha:////4AvbKtqCpWGC4/9vlaAOyQD+y56HOfLOpPpkD7K9YRsAAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
Running as SYSTEM
Building in workspace /var/root/.jenkins/workspace/data-minyao
using credential root
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:kirinisland/datapipe.git # timeout=10
Fetching upstream changes from git@github.com:kirinisland/datapipe.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:kirinisland/datapipe.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 8862dc0b93faeb24f71cee4ff5c950ac2bc56c56 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 8862dc0b93faeb24f71cee4ff5c950ac2bc56c56 # timeout=10
Commit message: "update log"
 > git rev-list --no-walk 3b56e1389a2f9aeae1cb5cd946f48ff1e4df7866 # timeout=10
[data-minyao] $ /bin/sh -xe /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/jenkins7405176545371790435.sh
+ set -x
+ date_str=
+ '[' '' = '' ']'
++ date +%Y%m%d
+ date_str=20210418
+ output_dir=/Users/hongliang/media/storage/production_data/original_lyric/20210418
+ mkdir -pv /Users/hongliang/media/storage/production_data/original_lyric/20210418
+ '[' true = true ']'
+ echo 'Fetch with proxy!'
Fetch with proxy!
+ python3 runner_qq.py --method search --query $'\346\260\221\350\260\243' --output-suffix minyao --dump-raw 1 --dump-seg 0 --proxy
INFO:[DataPipeline]:Start crawling for query: 民谣
INFO:[DataPipeline]:Processing playlist page: 0, found 46 playlists
INFO:[DataPipeline]:Processing playlist page: 1, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 2, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 3, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 4, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 5, found 43 playlists
INFO:[DataPipeline]:Processing playlist page: 6, found 47 playlists
INFO:[DataPipeline]:Processing playlist page: 7, found 45 playlists
INFO:[DataPipeline]:Processing playlist page: 8, found 44 playlists
INFO:[DataPipeline]:Processing playlist page: 9, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 10, found 46 playlists
INFO:[DataPipeline]:Processing playlist page: 11, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 12, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 13, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 14, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 15, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 16, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 17, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 18, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 19, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 20, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 21, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 22, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 23, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 24, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 25, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 26, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 27, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 28, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 29, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 30, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 31, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 32, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 33, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 34, found 20 playlists
INFO:[DataPipeline]:Processing playlist page: 35, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 36, found 17 playlists
INFO:[DataPipeline]:Processing playlist page: 37, found 46 playlists
INFO:[DataPipeline]:Processing playlist page: 38, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 39, found 46 playlists
INFO:[DataPipeline]:Processing playlist page: 40, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 41, found 46 playlists
INFO:[DataPipeline]:Processing playlist page: 42, found 20 playlists
INFO:[DataPipeline]:Processing playlist page: 43, found 18 playlists
INFO:[DataPipeline]:Processing playlist page: 44, found 28 playlists
INFO:[DataPipeline]:Processing playlist page: 45, found 20 playlists
INFO:[DataPipeline]:Processing playlist page: 46, found 27 playlists
INFO:[DataPipeline]:Processing playlist page: 47, found 18 playlists
INFO:[DataPipeline]:Processing playlist page: 48, found 42 playlists
INFO:[DataPipeline]:Processing playlist page: 49, found 40 playlists
INFO:[DataPipeline]:Processing playlist page: 50, found 0 playlists
INFO:[DataPipeline]:Total playlists found about topic: 民谣: 2183
INFO:[DataPipeline]:PlayList: [813783126] 听了这些歌爱上了民谣 (0/2183) has 100 songs.
INFO:[DataPipeline]:PlayList: [1167623725] 「民谣」孤独的旅人，诗意的远方 (1/2183) has 175 songs.
INFO:[DataPipeline]:PlayList: [2370564757] 「民谣」是毒药，也是良药 (2/2183) has 99 songs.
INFO:[DataPipeline]:PlayList: [7559412657] 华语民谣大合集，首首入心 (3/2183) has 97 songs.
INFO:[DataPipeline]:PlayList: [861218535] 400位华语民谣歌手，一人一首入耳曲 (4/2183) has 401 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=104923194&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 58, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=104923194&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 68, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ProxyError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=104923194&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))")),)
INFO:[DataPipeline]:PlayList: [5109299040] 民谣诗酒铺 (5/2183) has 40 songs.
INFO:[DataPipeline]:PlayList: [3269004721] 民谣如酒&#32;入喉醉心 (6/2183) has 251 songs.
INFO:[DataPipeline]:PlayList: [7685581382] 民谣与酒&#32;&#124;&#32;姑娘·吉他·南北方 (7/2183) has 382 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=228892508&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 58, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=228892508&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 68, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ProxyError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=228892508&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))")),)
INFO:[DataPipeline]:PlayList: [7771832630] 百首民谣：一把吉他&#32;四海为家 (8/2183) has 145 songs.
INFO:[DataPipeline]:PlayList: [3613980452] 站内评论999&#43;民谣歌曲 (9/2183) has 99 songs.
INFO:[DataPipeline]:Sleep for: 99
INFO:[DataPipeline]:PlayList: [7445947618] 2020年抖音精选民谣（持续更新） (10/2183) has 75 songs.
INFO:[DataPipeline]:PlayList: [2058943165] 民谣集：20岁时变成了一个用故事下酒的人 (11/2183) has 109 songs.
INFO:[DataPipeline]:PlayList: [2944763610] 人生所有的酒，都不如听民谣一首 (12/2183) has 179 songs.
INFO:[DataPipeline]:PlayList: [7488008022] 治愈民谣丨愿世间美好如约而至 (13/2183) has 24 songs.
INFO:[DataPipeline]:PlayList: [7587532725] 抖音民谣精选&#32;&#124;&#32;倾听你的故事 (14/2183) has 60 songs.
INFO:[DataPipeline]:PlayList: [7280726307] 华语&#32;&#124;&#32;暖心民谣 (15/2183) has 29 songs.
INFO:[DataPipeline]:PlayList: [7682677139] 伤感民谣&#32;&#124;&#32;往事随风，活在当下 (16/2183) has 50 songs.
INFO:[DataPipeline]:PlayList: [7552830303] 民谣&#32;&#58;&#32;历尽山海，唱遍天涯 (17/2183) has 66 songs.
INFO:[DataPipeline]:PlayList: [7631727991] 睡前民谣｜一个人的安静不被打扰 (18/2183) has 50 songs.
INFO:[DataPipeline]:PlayList: [7626536687] 民谣：十里春风，不如你扣弦一曲 (19/2183) has 99 songs.
INFO:[DataPipeline]:Sleep for: 171
INFO:[DataPipeline]:PlayList: [3536845247] 欧美｜清透舒适的民谣小调 (20/2183) has 40 songs.
INFO:[DataPipeline]:PlayList: [7530160095] 诗酒如歌，收藏10w&#43;华语民谣 (21/2183) has 180 songs.
INFO:[DataPipeline]:PlayList: [7581152954] 【民谣】听他人故事，走自己人生 (22/2183) has 87 songs.
INFO:[DataPipeline]:PlayList: [3762511678] 「抖音」抖友都在听的热门华语民谣 (23/2183) has 173 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=785999&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 58, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=785999&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 68, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ProxyError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=785999&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))")),)
INFO:[DataPipeline]:PlayList: [4203206457] 民谣：南方的我&#32;北方的你 (24/2183) has 247 songs.
INFO:[DataPipeline]:PlayList: [7670846435] 听一首民谣，说一个故事 (25/2183) has 92 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=877593&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 58, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=877593&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 68, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ProxyError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=877593&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))")),)
INFO:[DataPipeline]:PlayList: [7534581780] 民谣是枪，孤独上膛 (26/2183) has 123 songs.
INFO:[DataPipeline]:PlayList: [7565349105] 精选民谣&#32;&#124;&#32;故事和酒，唯独差你 (27/2183) has 98 songs.
INFO:[DataPipeline]:PlayList: [7704916742] 有没有一曲民谣扣了你的心弦？ (28/2183) has 32 songs.
INFO:[DataPipeline]:PlayList: [7721442801] 清新民谣！吉他陪伴，暖心相随 (29/2183) has 80 songs.
INFO:[DataPipeline]:Sleep for: 176
INFO:[DataPipeline]:PlayList: [7526194842] 民谣热歌：站内收藏100w&#43; (30/2183) has 53 songs.
INFO:[DataPipeline]:PlayList: [7670394209] 民谣丨唱自己的歌，做别人的梦 (31/2183) has 61 songs.
INFO:[DataPipeline]:PlayList: [3154139331] 民谣：低吟浅唱小众的情怀 (32/2183) has 140 songs.
INFO:[DataPipeline]:PlayList: [7743658818] 宅家必备，百首民谣一次听个够！ (33/2183) has 110 songs.
INFO:[DataPipeline]:PlayList: [7644406389] 民谣｜岁月是枪，孤独上膛 (34/2183) has 90 songs.
INFO:[DataPipeline]:PlayList: [7637949811] 民谣｜听的是故事，触动的是心灵 (35/2183) has 80 songs.
INFO:[DataPipeline]:PlayList: [7670221889] 民谣：灯火阑珊，是谁在伤感 (36/2183) has 45 songs.
INFO:[DataPipeline]:PlayList: [7695408423] 民谣&#124;无论去哪，都是该去的地方 (37/2183) has 67 songs.
INFO:[DataPipeline]:PlayList: [7550720459] 民谣丨听懂是经历，听不懂是幸运 (38/2183) has 67 songs.
INFO:[DataPipeline]:PlayList: [7562193888] 民谣丨内心深处的宁静 (39/2183) has 30 songs.
INFO:[DataPipeline]:Sleep for: 60
